# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build , Test and Deploy Library application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Checkout the Repository
      uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name : Install Dependencies
      run : npm install
    - name : Install Playwright Browsers
      run : npx playwright install
    - name: Change the backend to localhost for testing purposes
      run : echo "export const settings = { host : \"https://localhost:3030\"}" > src/config.js
    - name: Start server
      run : npm run server &
    - name: Start Front End
      run : npm run start &
    - name: Start Tests
      run : npm run test 
   
